# **Data Preprocessing**
#### **Prepare the data for machine learning and Gnn**

In [1]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
#Load Data
df = pd.read_csv(r"E:\BDA\Summer 2026\Data\featured_data\master_with_target.csv")
df["Date"] = pd.to_datetime(df["Date"])
df.head()

,Date,NIFTY50,NIFTY_AUTO,NIFTY_BANK,NIFTY_ENERGY,NIFTY_FMCG,NIFTY_IT,NIFTY_METAL,NIFTY_PHARMA,NIFTY_REALTY,...,CooperationCount,NIFTY50_Target,NIFTY_AUTO_Target,NIFTY_BANK_Target,NIFTY_ENERGY_Target,NIFTY_FMCG_Target,NIFTY_IT_Target,NIFTY_METAL_Target,NIFTY_PHARMA_Target,NIFTY_REALTY_Target
0,2018-02-15,10545.500000,11335.650391,25340.955078,13879.000000,26645.099609,12420.000000,4024.750000,9249.200195,334.700012,...,28527,0,0,1,1,1,1,1,0,0
1,2018-02-16,10452.299805,11306.799805,25424.054688,13968.099609,26733.500000,12456.500000,4052.550049,9207.500000,331.299988,...,26924,0,0,0,0,0,0,0,0,0
2,2018-02-20,10360.400391,10976.650391,25058.259766,13777.750000,26411.400391,12331.400391,3923.399902,9027.900391,322.549988,...,29749,1,0,0,0,0,1,1,0,0
3,2018-02-21,10397.450195,10962.900391,24874.111328,13748.200195,26356.400391,12372.000000,3966.500000,9020.750000,320.850006,...,28595,0,0,1,1,1,1,0,0,0
4,2018-02-22,10382.700195,10942.200195,24936.410156,13818.500000,26572.000000,12660.049805,3912.100098,8843.400391,318.649994,...,28274,1,0,1,0,0,1,0,1,1

In [3]:
#Data info
print(df.info())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1940 entries, 0 to 1939
Columns: 145 entries, Date to NIFTY_REALTY_Target
dtypes: datetime64[ns](1), float64(111), int64(33)
memory usage: 2.1 MB
None
(1940, 145)

In [3]:
df.columns.to_list()

['Date',
 'NIFTY50',
 'NIFTY_AUTO',
 'NIFTY_BANK',
 'NIFTY_ENERGY',
 'NIFTY_FMCG',
 'NIFTY_IT',
 'NIFTY_METAL',
 'NIFTY_PHARMA',
 'NIFTY_REALTY',
 'NIFTY50_Return',
 'NIFTY_AUTO_Return',
 'NIFTY_BANK_Return',
 'NIFTY_ENERGY_Return',
 'NIFTY_FMCG_Return',
 'NIFTY_IT_Return',
 'NIFTY_METAL_Return',
 'NIFTY_PHARMA_Return',
 'NIFTY_REALTY_Return',
 'NIFTY50_Log_Return',
 'NIFTY_AUTO_Log_Return',
 'NIFTY_BANK_Log_Return',
 'NIFTY_ENERGY_Log_Return',
 'NIFTY_FMCG_Log_Return',
 'NIFTY_IT_Log_Return',
 'NIFTY_METAL_Log_Return',
 'NIFTY_PHARMA_Log_Return',
 'NIFTY_REALTY_Log_Return',
 'NIFTY50_MA30',
 'NIFTY_AUTO_MA30',
 'NIFTY_BANK_MA30',
 'NIFTY_ENERGY_MA30',
 'NIFTY_FMCG_MA30',
 'NIFTY_IT_MA30',
 'NIFTY_METAL_MA30',
 'NIFTY_PHARMA_MA30',
 'NIFTY_REALTY_MA30',
 'NIFTY50_Volatility',
 'NIFTY_AUTO_Volatility',
 'NIFTY_BANK_Volatility',
 'NIFTY_ENERGY_Volatility',
 'NIFTY_FMCG_Volatility',
 'NIFTY_IT_Volatility',
 'NIFTY_METAL_Volatility',
 'NIFTY_PHARMA_Volatility',
 'NIFTY_REALTY_Volatility',
 'NIFTY50_Momentum',
 'NIFTY_AUTO_Momentum',
 'NIFTY_BANK_Momentum',
 'NIFTY_ENERGY_Momentum',
 'NIFTY_FMCG_Momentum',
 'NIFTY_IT_Momentum',
 'NIFTY_METAL_Momentum',
 'NIFTY_PHARMA_Momentum',
 'NIFTY_REALTY_Momentum',
 'NIFTY50_RS',
 'NIFTY_AUTO_RS',
 'NIFTY_BANK_RS',
 'NIFTY_ENERGY_RS',
 'NIFTY_FMCG_RS',
 'NIFTY_IT_RS',
 'NIFTY_METAL_RS',
 'NIFTY_PHARMA_RS',
 'NIFTY_REALTY_RS',
 'NIFTY50_RSI',
 'NIFTY_AUTO_RSI',
 'NIFTY_BANK_RSI',
 'NIFTY_ENERGY_RSI',
 'NIFTY_FMCG_RSI',
 'NIFTY_IT_RSI',
 'NIFTY_METAL_RSI',
 'NIFTY_PHARMA_RSI',
 'NIFTY_REALTY_RSI',
 'NIFTY50_Drawdown',
 'NIFTY_AUTO_Drawdown',
 'NIFTY_BANK_Drawdown',
 'NIFTY_ENERGY_Drawdown',
 'NIFTY_FMCG_Drawdown',
 'NIFTY_IT_Drawdown',
 'NIFTY_METAL_Drawdown',
 'NIFTY_PHARMA_Drawdown',
 'NIFTY_REALTY_Drawdown',
 'NIFTY50_Price_MA30',
 'NIFTY_AUTO_Price_MA30',
 'NIFTY_BANK_Price_MA30',
 'NIFTY_ENERGY_Price_MA30',
 'NIFTY_FMCG_Price_MA30',
 'NIFTY_IT_Price_MA30',
 'NIFTY_METAL_Price_MA30',
 'NIFTY_PHARMA_Price_MA30',
 'NIFTY_REALTY_Price_MA30',
 'gold',
 'oil',
 'usd_inr',
 'vix',
 'gold_Return',
 'oil_Return',
 'usd_inr_Return',
 'vix_Return',
 'gold_MA30',
 'oil_MA30',
 'usd_inr_MA30',
 'vix_MA30',
 'USA_Conflict',
 'India_Conflict',
 'China_Conflict',
 'Russia_Conflict',
 'Pakistan_Conflict',
 'Israel_Conflict',
 'Iran_Conflict',
 'USA_Events',
 'China_Events',
 'Russia_Events',
 'India_Event',
 'Pakistan_Events',
 'Israel_Events',
 'Iran_Events',
 'USA_Tone',
 'China_Tone',
 'Russia_Tone',
 'Pakistan_Tone',
 'Israel_Tone',
 'India_Tone',
 'Iran_Tone',
 'AvgTone',
 'AvgGoldstein',
 'EventCount',
 'TotalMentions',
 'ProtestCount',
 'ThreatCount',
 'MilitaryCount',
 'AssaultCount',
 'FightCount',
 'MassViolenceCount',
 'DiplomacyCount',
 'CooperationCount',
 'NIFTY50_Target',
 'NIFTY_AUTO_Target',
 'NIFTY_BANK_Target',
 'NIFTY_ENERGY_Target',
 'NIFTY_FMCG_Target',
 'NIFTY_IT_Target',
 'NIFTY_METAL_Target',
 'NIFTY_PHARMA_Target',
 'NIFTY_REALTY_Target']

In [6]:
# Define Target Columns
target_columns = [
    "NIFTY50_Target",
    "NIFTY_AUTO_Target",
    "NIFTY_BANK_Target",
    "NIFTY_ENERGY_Target",
    "NIFTY_FMCG_Target",
    "NIFTY_IT_Target",
    "NIFTY_METAL_Target",
    "NIFTY_PHARMA_Target",
    "NIFTY_REALTY_Target"
]

In [ ]:
# Select Features X
X = df.drop(columns=["Date"] + target_columns)
print(X.shape)
X.head()

(1940, 135)

,NIFTY50,NIFTY_AUTO,NIFTY_BANK,NIFTY_ENERGY,NIFTY_FMCG,NIFTY_IT,NIFTY_METAL,NIFTY_PHARMA,NIFTY_REALTY,NIFTY50_Return,...,EventCount,TotalMentions,ProtestCount,ThreatCount,MilitaryCount,AssaultCount,FightCount,MassViolenceCount,DiplomacyCount,CooperationCount
0,10545.500000,11335.650391,25340.955078,13879.000000,26645.099609,12420.000000,4024.750000,9249.200195,334.700012,0.004247,...,309524,1854918,2372,4721,877,4965,21715,188,123611,28527
1,10452.299805,11306.799805,25424.054688,13968.099609,26733.500000,12456.500000,4052.550049,9207.500000,331.299988,-0.008838,...,299463,1764924,2456,4903,1024,4393,19265,224,120799,26924
2,10360.400391,10976.650391,25058.259766,13777.750000,26411.400391,12331.400391,3923.399902,9027.900391,322.549988,-0.001734,...,323982,1953820,3238,5540,1228,5192,20617,206,130143,29749
3,10397.450195,10962.900391,24874.111328,13748.200195,26356.400391,12372.000000,3966.500000,9020.750000,320.850006,0.003576,...,324728,1941653,3086,5085,967,5432,20555,231,131376,28595
4,10382.700195,10942.200195,24936.410156,13818.500000,26572.000000,12660.049805,3912.100098,8843.400391,318.649994,-0.001419,...,319417,1917368,3250,5159,926,5757,19482,338,128182,28274

In [8]:
#Select target Y
Y = df[target_columns]
print(Y.shape)
Y.head()

(1940, 9)

,NIFTY50_Target,NIFTY_AUTO_Target,NIFTY_BANK_Target,NIFTY_ENERGY_Target,NIFTY_FMCG_Target,NIFTY_IT_Target,NIFTY_METAL_Target,NIFTY_PHARMA_Target,NIFTY_REALTY_Target
0,0,0,1,1,1,1,1,0,0
1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,1,1,0,0
3,0,0,1,1,1,1,0,0,0
4,1,0,1,0,0,1,0,1,1

In [12]:
# Check for Missing values
print(X.isnull().sum().sum())
print(Y.isnull().sum().sum())

0
0

In [14]:
# Train Test Split (not shuffling time-series data)
split = int(len(df)*0.8)

X_train = X.iloc[:split]
X_test = X.iloc[split:]

Y_train = Y.iloc[:split]
Y_test = Y.iloc[split:]

In [21]:
# Verifiey traning and testing pariods
print("Training Period:")
print(df.iloc[:split]["Date"].min())
print(df.iloc[:split]["Date"].max())

print("\nTesting Period:")
print(df.iloc[split:]["Date"].min())
print(df.iloc[split:]["Date"].max())

Training Period:
2018-02-15 00:00:00
2024-08-14 00:00:00

Testing Period:
2024-08-16 00:00:00
2026-03-27 00:00:00

In [22]:
# Check X_train,X_test,Y_train,Y_test
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(1552, 135)
(388, 135)
(1552, 9)
(388, 9)

In [23]:
# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

- my target Is already standerdize if I further scaled the values not longer become up or down 
- x_train = fit_transform (learns and then transform) , x_test=transform(took learned value then transform)

In [24]:
X_train_scaled

array([[-1.11842988, -0.0799116 , -1.08167205, ...,  1.20802327,
         1.68149314,  1.69639852],
       [-1.14125332, -0.08627087, -1.07171134, ...,  1.70053415,
         1.54565567,  1.32626452],
       [-1.16375821, -0.15904263, -1.11555726, ...,  1.45427871,
         1.99703027,  1.97855932],
       ...,
       [ 2.26136646,  3.12583185,  1.89286115, ...,  1.12593812,
        -1.0491686 , -0.90192833],
       [ 2.21043014,  3.15691117,  1.93215292, ...,  0.86600183,
        -0.67179934, -0.5525754 ],
       [ 2.21159335,  3.19050337,  1.94335418, ..., -0.00957307,
        -0.57847146, -0.39417744]])

In [25]:
# Convert back to data frame
X_train_scaled = pd.DataFrame(X_train_scaled,
                              columns=X.columns,
                              index=X_train.index)
X_test_scaled = pd.DataFrame(X_test_scaled,
                              columns=X.columns,
                              index=X_test.index)

In [26]:
X_train_scaled.head()

,NIFTY50,NIFTY_AUTO,NIFTY_BANK,NIFTY_ENERGY,NIFTY_FMCG,NIFTY_IT,NIFTY_METAL,NIFTY_PHARMA,NIFTY_REALTY,NIFTY50_Return,...,EventCount,TotalMentions,ProtestCount,ThreatCount,MilitaryCount,AssaultCount,FightCount,MassViolenceCount,DiplomacyCount,CooperationCount
0,-1.118430,-0.079912,-1.081672,-0.954719,-1.177796,-1.418611,-0.347365,-0.873129,-0.372508,0.323118,...,1.890232,2.113503,0.194144,1.540130,0.476169,1.622956,2.834183,1.208023,1.681493,1.696399
1,-1.141253,-0.086271,-1.071711,-0.943564,-1.168728,-1.414311,-0.334105,-0.885853,-0.387874,-0.817908,...,1.680185,1.786657,0.304039,1.756810,1.119760,1.035704,2.028383,1.700534,1.545656,1.326265
2,-1.163758,-0.159043,-1.115557,-0.967394,-1.201768,-1.429050,-0.395709,-0.940657,-0.427420,-0.198478,...,2.192077,2.472702,1.327105,2.515191,2.012908,1.856009,2.473053,1.454279,1.997030,1.978559
3,-1.154685,-0.162073,-1.137630,-0.971093,-1.207410,-1.424266,-0.375150,-0.942839,-0.435103,0.264596,...,2.207652,2.428513,1.128248,1.973490,0.870204,2.102409,2.452662,1.796300,2.056592,1.712100
4,-1.158297,-0.166636,-1.130163,-0.962292,-1.185294,-1.390329,-0.401099,-0.996956,-0.445046,-0.170944,...,2.096772,2.340313,1.342805,2.061591,0.690699,2.436075,2.099754,3.260152,1.902301,1.637981

In [27]:
output_folder = r"E:\BDA\Summer 2026\Preprossing"

X_train_scaled.to_csv(
    f"{output_folder}\\X_train.csv",
    index=False
)

X_test_scaled.to_csv(
    f"{output_folder}\\X_test.csv",
    index=False
)

Y_train.to_csv(
    f"{output_folder}\\Y_train.csv",
    index=False
)

Y_test.to_csv(
    f"{output_folder}\\Y_test.csv",
    index=False
)

print("Processed datasets saved successfully!")

Processed datasets saved successfully!

1. Load the master data with target variable
2. split master data in X (all the features escapt Date and Target columns) & Y (target features)
3. split data in X_train,X_test,Y_train,Y_test in 80,20
4. Standard Scale X_train,X_test
5. conver back to dataframe
6. Save all the dataframes into csv files