# **Combine all clean macro data**

In [1]:
import pandas as pd
import numpy as np
import os

In [20]:
input_folder = r"E:\BDA\Summer 2026\Data\cleaned_data\macro_cleaned_data"

combined_macro = pd.DataFrame()

for file in os.listdir(input_folder):

    if file.endswith(".csv"):

        path = os.path.join(input_folder, file)

        df = pd.read_csv(path)

        # Move dates from Price to Date
        df["Date"] = df["Price"]

        # Remove the old Price column
        df = df.drop(columns=["Price"])

        df = df[df["Date"] != "Date"]


        df["Date"] = pd.to_datetime(df["Date"])

        df = df.reset_index(drop=True)

        # Remove filename parts
        macro = os.path.splitext(file)[0]
        macro = macro.replace("_data_clean", "")

        if combined_macro.empty:
            combined_macro["Date"] = df["Date"]

        combined_macro[macro] = df["Close"]

combined_macro.head()

        Date         gold        oil    usd_inr    vix
0 2018-01-02  1313.699951  66.570000  63.840801  13.35
1 2018-01-03  1316.199951  67.839996  63.867599  13.69
2 2018-01-04  1319.400024  68.070000  63.459999  13.62
3 2018-01-05  1320.300049  67.620003  63.419102  13.42
4 2018-01-08  1318.599976  67.779999  63.369598  13.11

## **Save combain**

In [21]:
combined_macro.to_csv(
    r"E:\BDA\Summer 2026\Data\featured_data\combined_macro_close_prices.csv",
    index=False
)

### **Feature Engineering**

#### **Load combined mecro data**

In [23]:
df_macro = pd.read_csv(
    r"E:\BDA\Summer 2026\Data\featured_data\combined_macro_close_prices.csv"
)

df_macro["Date"] = pd.to_datetime(df_macro["Date"])

macro_columns = df_macro.columns.drop("Date")

In [24]:
df_macro

           Date         gold        oil    usd_inr    vix
0    2018-01-02  1313.699951  66.570000  63.840801  13.35
1    2018-01-03  1316.199951  67.839996  63.867599  13.69
2    2018-01-04  1319.400024  68.070000  63.459999  13.62
3    2018-01-05  1320.300049  67.620003  63.419102  13.42
4    2018-01-08  1318.599976  67.779999  63.369598  13.11
...         ...          ...        ...        ...    ...
2125 2026-06-16  4330.899902  87.330002  91.563400    NaN
2126 2026-06-17  4358.899902  83.169998  92.008598    NaN
2127 2026-06-18  4224.100098  78.959999  92.123001    NaN
2128 2026-06-22  4181.899902  79.550003  91.786903    NaN
2129 2026-06-23  4129.899902  79.849998  91.936203    NaN

[2130 rows x 5 columns]

#### **Calculate return**

In [25]:
for macro in macro_columns:

    df_macro[f"{macro}_Return"] = (
        df_macro[macro].pct_change(fill_method=None)
    )

In [26]:
df_macro

,Date,gold,oil,usd_inr,vix,gold_Return,oil_Return,usd_inr_Return,vix_Return
0,2018-01-02,1313.699951,66.570000,63.840801,13.35,NaN,NaN,NaN,NaN
1,2018-01-03,1316.199951,67.839996,63.867599,13.69,0.001903,0.019078,0.000420,0.025468
2,2018-01-04,1319.400024,68.070000,63.459999,13.62,0.002431,0.003390,-0.006382,-0.005113
3,2018-01-05,1320.300049,67.620003,63.419102,13.42,0.000682,-0.006611,-0.000644,-0.014684
4,2018-01-08,1318.599976,67.779999,63.369598,13.11,-0.001288,0.002366,-0.000781,-0.023100
...,...,...,...,...,...,...,...,...,...
2125,2026-06-16,4330.899902,87.330002,91.563400,NaN,0.000670,-0.033746,0.005312,NaN
2126,2026-06-17,4358.899902,83.169998,92.008598,NaN,0.006465,-0.047635,0.004862,NaN
2127,2026-06-18,4224.100098,78.959999,92.123001,NaN,-0.030925,-0.050619,0.001243,NaN
2128,2026-06-22,4181.899902,79.550003,91.786903,NaN,-0.009990,0.007472,-0.003648,NaN
2129,2026-06-23,4129.899902,79.849998,91.936203,NaN,-0.012435,0.003771,0.001627,NaN

#### **Create 30-Day Moving Average**

In [27]:
for macro in macro_columns:

    df_macro[f"{macro}_MA30"] = (
        df_macro[macro]
        .rolling(30)
        .mean()
    )

In [28]:
df_macro

,Date,gold,oil,usd_inr,vix,gold_Return,oil_Return,usd_inr_Return,vix_Return,gold_MA30,oil_MA30,usd_inr_MA30,vix_MA30
0,2018-01-02,1313.699951,66.570000,63.840801,13.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-03,1316.199951,67.839996,63.867599,13.69,0.001903,0.019078,0.000420,0.025468,NaN,NaN,NaN,NaN
2,2018-01-04,1319.400024,68.070000,63.459999,13.62,0.002431,0.003390,-0.006382,-0.005113,NaN,NaN,NaN,NaN
3,2018-01-05,1320.300049,67.620003,63.419102,13.42,0.000682,-0.006611,-0.000644,-0.014684,NaN,NaN,NaN,NaN
4,2018-01-08,1318.599976,67.779999,63.369598,13.11,-0.001288,0.002366,-0.000781,-0.023100,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,2026-06-16,4330.899902,87.330002,91.563400,NaN,0.000670,-0.033746,0.005312,NaN,4484.219979,100.508666,90.998653,NaN
2126,2026-06-17,4358.899902,83.169998,92.008598,NaN,0.006465,-0.047635,0.004862,NaN,4477.656649,99.675333,91.028326,NaN
2127,2026-06-18,4224.100098,78.959999,92.123001,NaN,-0.030925,-0.050619,0.001243,NaN,4462.396655,98.492666,91.047862,NaN
2128,2026-06-22,4181.899902,79.550003,91.786903,NaN,-0.009990,0.007472,-0.003648,NaN,4445.133325,97.481999,91.055483,NaN
2129,2026-06-23,4129.899902,79.849998,91.936203,NaN,-0.012435,0.003771,0.001627,NaN,4425.449992,96.768000,91.069990,NaN

#### **Remove Missing Values**

In [29]:
df_macro = df_macro.dropna().reset_index(drop=True)

In [30]:
df_macro

,Date,gold,oil,usd_inr,vix,gold_Return,oil_Return,usd_inr_Return,vix_Return,gold_MA30,oil_MA30,usd_inr_MA30,vix_MA30
0,2018-02-14,1355.500000,62.720001,64.440498,17.879999,0.020631,0.002077,0.003746,-0.070203,1329.999996,68.001000,63.762320,15.465000
1,2018-02-15,1352.099976,64.360001,64.211304,17.180000,-0.002508,0.026148,-0.003557,-0.039150,1331.279997,67.927333,63.774670,15.592667
2,2018-02-16,1353.199951,64.330002,64.283501,16.320000,0.000814,-0.000466,0.001124,-0.050058,1332.513330,67.810333,63.788533,15.680333
3,2018-02-20,1328.800049,64.839996,64.250099,16.379999,-0.018031,0.007928,-0.000520,0.003676,1332.826664,67.702667,63.814870,15.772333
4,2018-02-21,1330.000000,65.250000,64.025200,16.670000,0.000903,0.006323,-0.003500,0.017705,1333.149996,67.623667,63.835073,15.880667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2038,2026-03-24,4399.299805,112.190002,90.129997,13.190000,-0.001090,0.032582,0.002135,-0.012725,5004.976644,82.697334,89.012570,16.687000
2039,2026-03-25,4549.799805,99.940002,89.916901,12.670000,0.034210,-0.109190,-0.002364,-0.039424,4989.843311,83.760334,89.068950,16.553333
2040,2026-03-26,4375.500000,104.489998,89.792999,12.970000,-0.038309,0.045527,-0.001378,0.023678,4966.639974,84.942000,89.117196,16.431667
2041,2026-03-27,4492.000000,102.220001,90.252998,12.840000,0.026626,-0.021725,0.005123,-0.010023,4952.249967,86.056000,89.171146,16.298333
2042,2026-03-30,4526.000000,108.010002,90.577003,13.940000,0.007569,0.056643,0.003590,0.085670,4935.716634,87.343000,89.231200,16.144667

In [31]:
print(df_macro.head())

print(df_macro.info())

print(df_macro.isnull().sum())

        Date         gold        oil    usd_inr        vix  gold_Return  \
0 2018-02-14  1355.500000  62.720001  64.440498  17.879999     0.020631
1 2018-02-15  1352.099976  64.360001  64.211304  17.180000    -0.002508
2 2018-02-16  1353.199951  64.330002  64.283501  16.320000     0.000814
3 2018-02-20  1328.800049  64.839996  64.250099  16.379999    -0.018031
4 2018-02-21  1330.000000  65.250000  64.025200  16.670000     0.000903

   oil_Return  usd_inr_Return  vix_Return    gold_MA30   oil_MA30  \
0    0.002077        0.003746   -0.070203  1329.999996  68.001000
1    0.026148       -0.003557   -0.039150  1331.279997  67.927333
2   -0.000466        0.001124   -0.050058  1332.513330  67.810333
3    0.007928       -0.000520    0.003676  1332.826664  67.702667
4    0.006323       -0.003500    0.017705  1333.149996  67.623667

   usd_inr_MA30   vix_MA30
0     63.762320  15.465000
1     63.774670  15.592667
2     63.788533  15.680333
3     63.814870  15.772333
4     63.835073  15.880667
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2043 entries, 0 to 2042
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2043 non-null   datetime64[ns]
 1   gold            2043 non-null   float64
 2   oil             2043 non-null   float64
 3   usd_inr         2043 non-null   float64
 4   vix             2043 non-null   float64
 5   gold_Return     2043 non-null   float64
 6   oil_Return      2043 non-null   float64
 7   usd_inr_Return  2043 non-null   float64
 8   vix_Return      2043 non-null   float64
 9   gold_MA30       2043 non-null   float64
 10  oil_MA30        2043 non-null   float64
 11  usd_inr_MA30    2043 non-null   float64
 12  vix_MA30        2043 non-null   float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 207.6 KB
None
Date              0
gold              0
oil               0
usd_inr           0
vix               0
gold_Return       0
oil_Return        0
usd_inr_Return    0
vix_Return        0
gold_MA30         0
oil_MA30          0
usd_inr_MA30      0
vix_MA30          0
dtype: int64

## **Save Data**

In [32]:
df_macro.to_csv(
    r"E:\BDA\Summer 2026\Data\featured_data\featured_macro_data.csv",
    index=False
)