# **Combine all clean sector data based on the close price**

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import pandas as pd
import os

input_folder = r"E:\BDA\Summer 2026\Data\cleaned_data\sector_cleaned_data"

combined_df = pd.DataFrame()

for file in os.listdir(input_folder):

    if file.endswith(".csv"):

        path = os.path.join(input_folder, file)

        df = pd.read_csv(path)

        df["Date"] = pd.to_datetime(df["Date"])

        sector = os.path.splitext(file)[0]
        sector = sector.replace("_data_clean", "")


        if combined_df.empty:
            combined_df["Date"] = df["Date"]

        combined_df[sector] = df["Close"]

combined_df

,Date,NIFTY50,NIFTY_AUTO,NIFTY_BANK,NIFTY_ENERGY,NIFTY_FMCG,NIFTY_IT,NIFTY_METAL,NIFTY_PHARMA,NIFTY_REALTY
0,2018-01-02,10442.200195,11890.500000,25317.804688,14138.950195,26686.349609,11565.750000,3919.199951,9618.150391,347.700012
1,2018-01-03,10443.200195,11927.150391,25337.955078,14162.400391,26533.500000,11602.349609,3942.850098,9565.799805,343.850006
2,2018-01-04,10504.799805,11866.799805,25318.304688,14157.799805,26648.400391,11586.700195,4000.199951,9519.549805,345.450012
3,2018-01-05,10558.849609,11843.250000,25462.302734,14247.250000,26689.599609,11590.799805,4112.000000,9633.599609,344.799988
4,2018-01-08,10623.599609,11929.599609,25601.552734,14249.900391,26914.300781,11633.549805,4130.399902,9701.049805,347.299988
...,...,...,...,...,...,...,...,...,...,...
2080,2026-06-15,23853.900391,NaN,56814.800781,NaN,NaN,27795.750000,NaN,24220.099609,NaN
2081,2026-06-16,23989.150391,NaN,57198.800781,NaN,NaN,28067.900391,NaN,24157.849609,NaN
2082,2026-06-17,24085.699219,NaN,57297.148438,NaN,NaN,28568.099609,NaN,24146.550781,NaN
2083,2026-06-18,24168.000000,NaN,57585.050781,NaN,NaN,28809.550781,NaN,24282.199219,NaN
2084,2026-06-19,24013.099609,NaN,57963.800781,NaN,NaN,28466.449219,NaN,24460.300781,NaN

In [3]:
combined_df.to_csv(
    r"E:\BDA\Summer 2026\Data\featured_data\combined_sector_close_prices.csv",
    index=False
)

## 3. **Feature Engineering**

In [4]:

df_sector = pd.read_csv(
    r"E:\BDA\Summer 2026\Data\featured_data\combined_sector_close_prices.csv"
)

df_sector["Date"] = pd.to_datetime(df_sector["Date"])

sector_columns = df_sector.columns.drop("Date")

In [5]:
for col in df_sector.columns:
    print(col)

Date
NIFTY50
NIFTY_AUTO
NIFTY_BANK
NIFTY_ENERGY
NIFTY_FMCG
NIFTY_IT
NIFTY_METAL
NIFTY_PHARMA
NIFTY_REALTY

### **Return**

In [6]:
for sector in sector_columns:

    df_sector[f"{sector}_Return"] = (
        df_sector[sector].pct_change(fill_method=None)
    )

In [7]:
df_sector

,Date,NIFTY50,NIFTY_AUTO,NIFTY_BANK,NIFTY_ENERGY,NIFTY_FMCG,NIFTY_IT,NIFTY_METAL,NIFTY_PHARMA,NIFTY_REALTY,NIFTY50_Return,NIFTY_AUTO_Return,NIFTY_BANK_Return,NIFTY_ENERGY_Return,NIFTY_FMCG_Return,NIFTY_IT_Return,NIFTY_METAL_Return,NIFTY_PHARMA_Return,NIFTY_REALTY_Return
0,2018-01-02,10442.200195,11890.500000,25317.804688,14138.950195,26686.349609,11565.750000,3919.199951,9618.150391,347.700012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-03,10443.200195,11927.150391,25337.955078,14162.400391,26533.500000,11602.349609,3942.850098,9565.799805,343.850006,0.000096,0.003082,0.000796,0.001659,-0.005728,0.003164,0.006034,-0.005443,-0.011073
2,2018-01-04,10504.799805,11866.799805,25318.304688,14157.799805,26648.400391,11586.700195,4000.199951,9519.549805,345.450012,0.005899,-0.005060,-0.000776,-0.000325,0.004330,-0.001349,0.014545,-0.004835,0.004653
3,2018-01-05,10558.849609,11843.250000,25462.302734,14247.250000,26689.599609,11590.799805,4112.000000,9633.599609,344.799988,0.005145,-0.001985,0.005688,0.006318,0.001546,0.000354,0.027949,0.011981,-0.001882
4,2018-01-08,10623.599609,11929.599609,25601.552734,14249.900391,26914.300781,11633.549805,4130.399902,9701.049805,347.299988,0.006132,0.007291,0.005469,0.000186,0.008419,0.003688,0.004475,0.007002,0.007251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,2026-06-15,23853.900391,NaN,56814.800781,NaN,NaN,27795.750000,NaN,24220.099609,NaN,0.009779,NaN,0.029687,NaN,NaN,-0.000909,NaN,-0.006561,NaN
2081,2026-06-16,23989.150391,NaN,57198.800781,NaN,NaN,28067.900391,NaN,24157.849609,NaN,0.005670,NaN,0.006759,NaN,NaN,0.009791,NaN,-0.002570,NaN
2082,2026-06-17,24085.699219,NaN,57297.148438,NaN,NaN,28568.099609,NaN,24146.550781,NaN,0.004025,NaN,0.001719,NaN,NaN,0.017821,NaN,-0.000468,NaN
2083,2026-06-18,24168.000000,NaN,57585.050781,NaN,NaN,28809.550781,NaN,24282.199219,NaN,0.003417,NaN,0.005025,NaN,NaN,0.008452,NaN,0.005618,NaN
2084,2026-06-19,24013.099609,NaN,57963.800781,NaN,NaN,28466.449219,NaN,24460.300781,NaN,-0.006409,NaN,0.006577,NaN,NaN,-0.011909,NaN,0.007335,NaN

## **Calculate log_return**

In [8]:
for sector in sector_columns:

    df_sector[f"{sector}_Log_Return"] = np.log(
        df_sector[sector] /
        df_sector[sector].shift(1)
    )

In [9]:
df_sector

,Date,NIFTY50,NIFTY_AUTO,NIFTY_BANK,NIFTY_ENERGY,NIFTY_FMCG,NIFTY_IT,NIFTY_METAL,NIFTY_PHARMA,NIFTY_REALTY,...,NIFTY_REALTY_Return,NIFTY50_Log_Return,NIFTY_AUTO_Log_Return,NIFTY_BANK_Log_Return,NIFTY_ENERGY_Log_Return,NIFTY_FMCG_Log_Return,NIFTY_IT_Log_Return,NIFTY_METAL_Log_Return,NIFTY_PHARMA_Log_Return,NIFTY_REALTY_Log_Return
0,2018-01-02,10442.200195,11890.500000,25317.804688,14138.950195,26686.349609,11565.750000,3919.199951,9618.150391,347.700012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-03,10443.200195,11927.150391,25337.955078,14162.400391,26533.500000,11602.349609,3942.850098,9565.799805,343.850006,...,-0.011073,0.000096,0.003078,0.000796,0.001657,-0.005744,0.003159,0.006016,-0.005458,-0.011135
2,2018-01-04,10504.799805,11866.799805,25318.304688,14157.799805,26648.400391,11586.700195,4000.199951,9519.549805,345.450012,...,0.004653,0.005881,-0.005073,-0.000776,-0.000325,0.004321,-0.001350,0.014441,-0.004847,0.004642
3,2018-01-05,10558.849609,11843.250000,25462.302734,14247.250000,26689.599609,11590.799805,4112.000000,9633.599609,344.799988,...,-0.001882,0.005132,-0.001986,0.005671,0.006298,0.001545,0.000354,0.027565,0.011909,-0.001883
4,2018-01-08,10623.599609,11929.599609,25601.552734,14249.900391,26914.300781,11633.549805,4130.399902,9701.049805,347.299988,...,0.007251,0.006114,0.007265,0.005454,0.000186,0.008384,0.003681,0.004465,0.006977,0.007224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,2026-06-15,23853.900391,NaN,56814.800781,NaN,NaN,27795.750000,NaN,24220.099609,NaN,...,NaN,0.009731,NaN,0.029255,NaN,NaN,-0.000910,NaN,-0.006582,NaN
2081,2026-06-16,23989.150391,NaN,57198.800781,NaN,NaN,28067.900391,NaN,24157.849609,NaN,...,NaN,0.005654,NaN,0.006736,NaN,NaN,0.009743,NaN,-0.002573,NaN
2082,2026-06-17,24085.699219,NaN,57297.148438,NaN,NaN,28568.099609,NaN,24146.550781,NaN,...,NaN,0.004017,NaN,0.001718,NaN,NaN,0.017664,NaN,-0.000468,NaN
2083,2026-06-18,24168.000000,NaN,57585.050781,NaN,NaN,28809.550781,NaN,24282.199219,NaN,...,NaN,0.003411,NaN,0.005012,NaN,NaN,0.008416,NaN,0.005602,NaN
2084,2026-06-19,24013.099609,NaN,57963.800781,NaN,NaN,28466.449219,NaN,24460.300781,NaN,...,NaN,-0.006430,NaN,0.006556,NaN,NaN,-0.011981,NaN,0.007308,NaN

## **Moving Average**

In [10]:
for sector in sector_columns:

    df_sector[f"{sector}_MA30"] = (
        df_sector[sector]
        .rolling(30)
        .mean()
    )

## **Volatility**

In [11]:
for sector in sector_columns:

    df_sector[f"{sector}_Volatility"] = (
        df_sector[f"{sector}_Return"]
        .rolling(30)
        .std()
    )

## **Momentum**

In [12]:
for sector in sector_columns:

    df_sector[f"{sector}_Momentum"] = (
        df_sector[sector] /
        df_sector[sector].shift(10)
    ) - 1

## **Relative Strength**

In [14]:
for sector in sector_columns:

    df_sector[f"{sector}_RS"] = (
        df_sector[sector] /
        df_sector["NIFTY50"]
    )

## **RSI**

In [15]:
for sector in sector_columns:

    delta = df_sector[sector].diff()

    gain = delta.where(delta > 0, 0)

    loss = -delta.where(delta < 0, 0)

    avg_gain = gain.rolling(14).mean()

    avg_loss = loss.rolling(14).mean()

    rs = avg_gain / avg_loss

    df_sector[f"{sector}_RSI"] = 100 - (100/(1+rs))

## **Drawdown**

In [16]:
for sector in sector_columns:

    rolling_max = df_sector[sector].cummax()

    df_sector[f"{sector}_Drawdown"] = (
        df_sector[sector]-rolling_max
    )/rolling_max

## **Price / MA30**

In [17]:
for sector in sector_columns:

    df_sector[f"{sector}_Price_MA30"] = (
        df_sector[sector] /
        df_sector[f"{sector}_MA30"]
    )

## **Remove NaN**

In [18]:
df_sector = (
    df_sector
    .dropna()
    .reset_index(drop=True)
)

## **Save**

In [19]:
df_sector.to_csv(
    r"E:\BDA\Summer 2026\Data\featured_data\featured_sector_data.csv",
    index=False
)

In [20]:
print(df_sector.head())

print(df_sector.columns)

print(df_sector.shape)

        Date       NIFTY50    NIFTY_AUTO    NIFTY_BANK  NIFTY_ENERGY  \
0 2018-02-15  10545.500000  11335.650391  25340.955078  13879.000000
1 2018-02-16  10452.299805  11306.799805  25424.054688  13968.099609
2 2018-02-19  10378.400391  11114.549805  25163.607422  13801.049805
3 2018-02-20  10360.400391  10976.650391  25058.259766  13777.750000
4 2018-02-21  10397.450195  10962.900391  24874.111328  13748.200195

     NIFTY_FMCG      NIFTY_IT  NIFTY_METAL  NIFTY_PHARMA  NIFTY_REALTY  ...  \
0  26645.099609  12420.000000  4024.750000   9249.200195    334.700012  ...
1  26733.500000  12456.500000  4052.550049   9207.500000    331.299988  ...
2  26599.050781  12437.950195  3991.600098   9180.900391    327.200012  ...
3  26411.400391  12331.400391  3923.399902   9027.900391    322.549988  ...
4  26356.400391  12372.000000  3966.500000   9020.750000    320.850006  ...

   NIFTY_REALTY_Drawdown  NIFTY50_Price_MA30  NIFTY_AUTO_Price_MA30  \
0              -0.100873            0.982120               0.973997
1              -0.110007            0.973413               0.973248
2              -0.121021            0.966910               0.958769
3              -0.133512            0.965828               0.949239
4              -0.138079            0.969964               0.950699

   NIFTY_BANK_Price_MA30  NIFTY_ENERGY_Price_MA30  NIFTY_FMCG_Price_MA30  \
0               0.965981                 0.980016               0.981999
1               0.969043                 0.986759               0.985015
2               0.959305                 0.975777               0.980120
3               0.955779                 0.975209               0.973539
4               0.949634                 0.974271               0.972178

   NIFTY_IT_Price_MA30  NIFTY_METAL_Price_MA30  NIFTY_PHARMA_Price_MA30  \
0             0.996611                0.990843                 0.972631
1             0.997261                0.996789                 0.969463
2             0.993519                0.981867                 0.967813
3             0.983070                0.966586                 0.953714
4             0.984375                0.978521                 0.955247

   NIFTY_REALTY_Price_MA30
0                 0.969457
1                 0.960773
2                 0.950560
3                 0.939074
4                 0.936529

[5 rows x 91 columns]
Index(['Date', 'NIFTY50', 'NIFTY_AUTO', 'NIFTY_BANK', 'NIFTY_ENERGY',
       'NIFTY_FMCG', 'NIFTY_IT', 'NIFTY_METAL', 'NIFTY_PHARMA', 'NIFTY_REALTY',
       'NIFTY50_Return', 'NIFTY_AUTO_Return', 'NIFTY_BANK_Return',
       'NIFTY_ENERGY_Return', 'NIFTY_FMCG_Return', 'NIFTY_IT_Return',
       'NIFTY_METAL_Return', 'NIFTY_PHARMA_Return', 'NIFTY_REALTY_Return',
       'NIFTY50_Log_Return', 'NIFTY_AUTO_Log_Return', 'NIFTY_BANK_Log_Return',
       'NIFTY_ENERGY_Log_Return', 'NIFTY_FMCG_Log_Return',
       'NIFTY_IT_Log_Return', 'NIFTY_METAL_Log_Return',
       'NIFTY_PHARMA_Log_Return', 'NIFTY_REALTY_Log_Return', 'NIFTY50_MA30',
       'NIFTY_AUTO_MA30', 'NIFTY_BANK_MA30', 'NIFTY_ENERGY_MA30',
       'NIFTY_FMCG_MA30', 'NIFTY_IT_MA30', 'NIFTY_METAL_MA30',
       'NIFTY_PHARMA_MA30', 'NIFTY_REALTY_MA30', 'NIFTY50_Volatility',
       'NIFTY_AUTO_Volatility', 'NIFTY_BANK_Volatility',
       'NIFTY_ENERGY_Volatility', 'NIFTY_FMCG_Volatility',
       'NIFTY_IT_Volatility', 'NIFTY_METAL_Volatility',
       'NIFTY_PHARMA_Volatility', 'NIFTY_REALTY_Volatility',
       'NIFTY50_Momentum', 'NIFTY_AUTO_Momentum', 'NIFTY_BANK_Momentum',
       'NIFTY_ENERGY_Momentum', 'NIFTY_FMCG_Momentum', 'NIFTY_IT_Momentum',
       'NIFTY_METAL_Momentum', 'NIFTY_PHARMA_Momentum',
       'NIFTY_REALTY_Momentum', 'NIFTY50_RS', 'NIFTY_AUTO_RS', 'NIFTY_BANK_RS',
       'NIFTY_ENERGY_RS', 'NIFTY_FMCG_RS', 'NIFTY_IT_RS', 'NIFTY_METAL_RS',
       'NIFTY_PHARMA_RS', 'NIFTY_REALTY_RS', 'NIFTY50_RSI', 'NIFTY_AUTO_RSI',
       'NIFTY_BANK_RSI', 'NIFTY_ENERGY_RSI', 'NIFTY_FMCG_RSI', 'NIFTY_IT_RSI',
       'NIFTY_METAL_RSI', 'NIFTY_PHARMA_RSI', 'NIFTY_REALTY_RSI',
       'NIFTY50_Drawdown', 'NIFTY_AUTO_Drawdown', 'NIFTY_BANK_Drawdown',
       'NIFTY_ENERGY_Drawdown', 'NIFTY_FMCG_Drawdown', 'NIFTY_IT_Drawdown',
       'NIFTY_METAL_Drawdown', 'NIFTY_PHARMA_Drawdown',
       'NIFTY_REALTY_Drawdown', 'NIFTY50_Price_MA30', 'NIFTY_AUTO_Price_MA30',
       'NIFTY_BANK_Price_MA30', 'NIFTY_ENERGY_Price_MA30',
       'NIFTY_FMCG_Price_MA30', 'NIFTY_IT_Price_MA30',
       'NIFTY_METAL_Price_MA30', 'NIFTY_PHARMA_Price_MA30',
       'NIFTY_REALTY_Price_MA30'],
      dtype='object')
(2040, 91)